import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Header from '../components/Header'
import Hero from '../components/Hero'



const Home: NextPage = () => {
  return (
    <div  className='bg-[rgb(36,36,36)] h-screen text-white snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Billel Bahani's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/* Header */}
<Header/>
{/* hero esction */}
<section id="hero" className='snap-start'>
  <Hero/>
</section>
{/* about */}

<section id="about" className='snap-center'>
<About/>
</section>

{/* experience */}
{/* skilss */}
{/* projects */}
{/* contact me */}
    
    </div>
  )
}

export default Home
